### ISSUE TITLE
Converting text to HTML doesn't work for bold and italic

### ISSUE THREAD

**Issue by jakubkrolewski** [1gravity/Android-RTEditor#1]
1. I press "bold" in the demo activity
2. I type "Hello"
3. I see bold text "Hello"
4. mRTMessageField.getText(RTFormat.HTML) returns just plain text without any formatting (so `Hello` instead of `<b>Hello</b>`

**Comment by 1gravity** [comment]
I can't reproduce the issue, it works perfectly for ma, mRTMessageField.getText(RTFormat.HTML) returns html for Italic and Bold. The rich text editor is used in thousands of installations, if there was indeed that issue, my users would have complained already.

**Comment by jakubkrolewski** [comment]
The saved HTML file is completely empty, but that's another problem.
I tested on Nexus 5, Android 4.4.4.
I debugged the problem a little bit. In `ConverterSpannedToHtml` class, the line 251:
`List<CharacterStyle> spanList = Arrays.asList(text.getSpans(start, end, CharacterStyle.class));`
returns a single element list with
`0 = {StyleSpan@830046449792} 
 mStyle = 1`.
I don't know why it's not the BoldSpan as it was initially inserted, but that's what's there.
I propose to fix the problem by generating a html tag both from the BoldSpan and StyleSpan. It not only fixes the problem I describe, but also make the `ConverterSpannedToHtml` a better general purpose tool.

**Comment by 1gravity** [comment]
My Nexus 5 (although running Android M) has no such issue. Also tested it on an S3 running KitKat.

I don't want a workaround for an issue if the root cause isn't known and might lead to other (yet unknown) issues. As I said thousands of users use this component and no one has ever reported anything like this so let's find out what's special about your device.

Anything out of the ordinary on your device? rooted? custom 4.4.4? any suspicious apps installed? do you use a custom font?
What happens if you rotate the screen to landscape, is the bold text still there?

**Comment by jakubkrolewski** [comment]
After some more tests I've found the proper scenario to reproduce the problem:
1. Enable "don't keep activities" in the developer options
2. Start demo activity
3. Press "bold"
4. Type "Hello"
5. Press HOME
6. Go back to the demo application

That should be it.

**Comment by 1gravity** [comment]
I went for option 3 ;-).

The proper way to handle this is to save the view state in onSaveInstanceState and restore it in onRestoreInstanceState. By saving the text as html and restoring it from that html we can retain all custom span objects.

See 9ac8f6a151acdb73434e3f3c783e6e9d90f34bb8

**Comment by jakubkrolewski** [comment]
Indeed, the third solution sounds better:)
It works great now. Thanks :)
