### ISSUE TITLE
Underline issue

### ISSUE THREAD

**Issue by HamzehSoboh** [1gravity/Android-RTEditor#20]
The underline icon is activated (highlighted) without clicking on it. The text is underlined until you enter space then the underline is removed and the button is de-activated. This happens again as you continue typing.

**Comment by 1gravity** [comment]
It's underlined because the keyboard underlines it probably to show suggestions for auto-complete. Once you press space the suggestion disappears and the underline is removed by the keyboard.

**Comment by HamzehSoboh** [comment]
Thank you for your answer.
But kindly note that the underline button is highlighted when you start typing, and as you mentioned, the underline disappears and the highlight is removed from the button once space  is pressed. 
We just need to take rid of highlighting the underline button unless you press it. Thanks.

**Comment by 1gravity** [comment]
As I mentioned this is due to your device spell-checking or auto-completing your typing. When you start typing the keyboard will underline the typed text and once you enter a space the underlining will be removed. This is controlled by either the keyboard or the built-in spellchecker. The rich text editor toolbar merely reflects the fact that the text in focus in underlined. There's nothing to get rid, the toolbar HAS to reflect the formatting of the selected text.

**Comment by 1gravity** [comment]
I just committed a change that will prevent the underline button from being highlighted while typing.

**Comment by HamzehSoboh** [comment]
Thank so much !!!
