### ISSUE TITLE
How to get caret position in HTML

### ISSUE THREAD

**Issue by arthursz** [1gravity/Android-RTEditor#45]
Hey man!

How can i get the caret position in HTML?

Thanks!

**Comment by 1gravity** [comment]
I don't know what you mean with "caret position"? Do you want to insert a caret into HTML or what?

**Comment by arthursz** [comment]
Hi,

I what to get the position of the cursor in HTML. 

For example, if i have this text: 

> `This is a text`

If my cursor is before the word 'is' (This |is a text) the position of the cursor is 5 in plain text. But if i had the same sentence but with some HTML tags like this: 

> `<b><u>This</u></b> is my text`

And i put the cursor in the same position i will get position 5 in plain text, but i want to get the position in HTML which is 19 in this example.

So i want to get this position.

Thanks =D

**Comment by 1gravity** [comment]
Why would you want the position in the html text? The html is simply used as an format to persist the text and it could be any format that supports the formatting (rtf, markdown, xml...)?
I'm asking this question because I think you're trying to do something and I'm fairly certain that something might not be necessary or might have a much easier solution.
If you elaborate on what you're ultimately trying to achieve I might be able to point out a different approach.

**Comment by arthursz** [comment]
Oh Thanks! I'm trying to insert a image inside the text. I have the image path and i'm doing like this:

> `mRTMessageField.setRichTextEditing(true, rtHtmlBefore.getText() + "<img src=\"" + url +"\">" + rtHtmlAfter.getText());`

**Comment by 1gravity** [comment]
Why not insert the image directly into the Spanned text? That's what the editor is doing too when the user inserts an image.

**Comment by arthursz** [comment]
I tried but did not work =(

**Comment by 1gravity** [comment]
You can't insert an image from a url into the rich text editor. Android's ImageSpan doesn't support images that aren't stored locally so even if you could insert the image like that, it wouldn't render. You need to download the image first or else rewrite the ImageSpan class.

**Comment by arthursz** [comment]
Oh sorry, the image is stored locally.

**Comment by 1gravity** [comment]
That's how the editor itself inserts an image:
`
EventBus.getDefault().post( new MediaEvent(RTMedia) );
`

RTMedia can be an RTImageImpl:
`
new RTImageImpl(url)`

**Comment by arthursz** [comment]
It's not working =( Which method is called with this post? It's onEventMainThread(MediaEvent event) from the RTManager?

**Comment by 1gravity** [comment]
Don't even think of calling the onEventMainThread directly ;-).

You're right though, the method I mention above wouldn't work since it's using mActiveEditor to determine in what editor to insert the image. mActiveEditor is usually null though and is only set when the user does the insert manually.

The way to go is to use the insertImage(RTEditText, RTImage) method. It's currently private but can be made public. I tested it but it didn't work and I don't have the time to look into this atm but this is the way to go.

**Comment by arthursz** [comment]
No problem ;) Thank you very much!
