### ISSUE TITLE
If the user changes the font attributes, it is not been applied to the new text typed.

### ISSUE THREAD

**Issue by gbrizuela** [1gravity/Android-RTEditor#80]
There is an issue happening on newer versions of Android: If the user changes the font attributes, it is not been applied to the new text typed.  For example, if you change the size and then start typing, the new text that you type should be in the new size.  Right now it looks like it only works if you highlight text and then adjust the font settings.

Also, when the user long presses the text to select and highlight it, the user should be able to edit the current style, but now a menu with Copy and Paste options is been placed over the style editing toolbar, so the user cannot change the style of the text.

**Comment by long1EU** [comment]
Thats strange because I'm on Nougat and I can type with the same font. Can't you give more info?

**Comment by 1gravity** [comment]
I'm assuming there interference by the keyboard. I'm fairly certain text sizes, colors and font are applied whenever you enter a new word (beginning of a line and after entering a space or after punctuation. There are however problems when you try to change the formatting in mid-word because some (actually most) keyboards interfere with their auto-correct or suggest functionality and re-set the formatting to whatever it was at the beginning of the word. Maybe you can explain your test case in more detail. It certainly has nothing to do with the newer versions of Android (running Nougat here a well).

**Comment by gbrizuela** [comment]
Thank you for your answers. As you mentioned, I think it was related to the keyboard autosuggest. The edittext had on its style the autocorrection enabled. I turned off the autosuggestion and the autocorrection and it worked as expected.
